server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:helpdesk_db}?currentSchema=notification_schema
    username: ${POSTGRES_USER:helpdesk_user}
    password: ${POSTGRES_PASSWORD:helpdesk_password_secreta}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin_secret}
  config:
    import: 
    - "optional:file:../../../../../.env[.properties]"