services:
  postgres-db:
    image: postgres:15-alpine
    container_name: helpdesk-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: helpdesk-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  user-service:
    build: ./user-service
    container_name: helpdesk-user-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres-db
    restart: always

  ticket-service:
    build: ./ticket-service
    container_name: helpdesk-ticket-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-db
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - postgres-db
      - rabbitmq
    restart: always

  notification-service:
    build: ./notification-service
    container_name: helpdesk-notification-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres-db
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - postgres-db
      - rabbitmq
    restart: always

  api-gateway:
    build: ./gateway
    container_name: helpdesk-gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - TICKET_SERVICE_URL=http://ticket-service:8082
      - NOTIFICATION_SERVICE_URL=http://notification-service:8083
    depends_on:
      - user-service
      - ticket-service
      - notification-service
    restart: always