server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server: 
        webmvc:
          routes:
            - id: user-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1

            - id: ticket-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/tickets/**
              filters:
                - StripPrefix=1

            - id: notification-service-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: mappings, health